### ISSUE TITLE
190K open-domain samples selection

### ISSUE THREAD

**Issue by yilun-lee** [TsinghuaC3I/UltraMedical#2]
Thanks your Marvelous work!

I'd like to understand the method used to select the 190k open-domain samples from the provided datasets. The paper mentions the data composition and scoring criteria, but it doesn't detail the SFT data selection process.

For instance, it states that 58k samples come from UltraChat. However, there are 258k samples in UltraChat within [0-hero/Matter-0.1](https://huggingface.co/datasets/0-hero/Matter-0.1) and 773k in [stingning/ultrachat](https://huggingface.co/datasets/stingning/ultrachat).

Could anyone provide more information on how the open-domain data was selected?

Many thanks !

**Comment by iseesaw** [comment]
Thank you for your attention to this project. We randomly sample examples for each dataset (including ultrachat) within the 0-hero/Matter-0.1 project.

**Comment by yilun-lee** [comment]
Many thanks
